# Hugo variables
#
baseurl = "https://open-python-workshop.surge.sh/"
languageCode = "en-us"
title = "Redmond Python"
theme = "hugo-theme-bootstrap4-blog"
# number of posts to show on home/category/tag pages (Default: 10)
paginate = 5
copyright = "This workshop was initially created by [Philly's Python User Group](http://phillypythonworkshop.github.io/) and adapted by the [Redmond Python User Group](https://www.meetup.com/Redmond-Python-User-Group/)."

[permalinks]
  posts = "/:filename"
  post = "/:filename"

[[menu.sidebar]]
  name = "1. Machine Setup Steps"
  url = "/setup"
[[menu.sidebar]]
  name = "2. Practice"
  url = "/practice"
[[menu.sidebar]]
  name = "3. Projects"
  url = "/projects"
[[menu.sidebar]]
  name = "4. Full Workshop - Day 1"
  url = "/day_one_lesson"
[[menu.sidebar]]
  name = "5. Full Workshop - Day 2"
  url = "/day_two_lesson"


[[menu.navbar]]
  name = "Machine Setup"
  url = "/setup"
[[menu.navbar]]
  name = "2-Day Workshop"
  url = "/day_one_lesson"
[[menu.navbar]]
  name = "Short Workshop"
  url = "/short_workshop"


# custom navbar menu entry.   See the custom_navbar parameter below for
# details.

[params]
  author = "Fernando Medina Corey"
  description = "The Python User Group of Redmond, WA"
  date_format = "Mon Jan 02, 2006"
  custom_navbar = true

  # Disable the use of sub-resource integrity on CSS/JS assets
  # Useful if you're using a CDN or other host where you can't control cache headers
  disable_sri = false

  [params.sidebar]
    about = "Adapted from the [Philly PUG's workshop](http://phillypythonworkshop.github.io/)."

    # How many posts to show on the sidebar (Default: 5)
    num_recent_posts = 3

  [params.social]
    twitter = "fmc_sea"
